version: '3'

services:
  proxy:
    build:
      context: ./nginx
    container_name: proxy
    hostname: proxy
    #entrypoint: dockerize -wait http://node:3000 -timeout 20s docker-entrypoint.sh
    ports:
      - "8080:8080"
    networks:
      - proxy-network
    depends_on:
      - node

  node:
    build:
      context: ./nodejs
    container_name: node
    hostname: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    networks:
      - proxy-network
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
